### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by PenguinPaul** [Team-VerseBot/versebot#1]
We could really use some documentation, especially for install.  I don't know where to start.

**Comment by shackra** [comment]
Well, it should go to the repository's wiki pages, unless someone else have any better recommendation for storing the documentation

**Comment by adamgrieger** [comment]
You would have to ask @matthieugrieger about setting up VerseBot. I was never involved in maintaining it, so he would have to explain how to install it. I have a faint idea of how it works, but I have never tried it myself.

**Comment by matthieugrieger** [comment]
I'll get some docs up as soon as I can. It's not too bad.

Mainly you just need to install some dependencies via `pip` and set up a Postgres database (if that bit of code is going to be kept).

**Comment by matthieugrieger** [comment]
I created a short setup guide in [SETUP.md](https://github.com/Team-VerseBot/versebot/blob/master/SETUP.md).

Let me know if I need to add more detail or if I forgot something.

**Comment by adamgrieger** [comment]
@PenguinPaul, I don't think you would need to worry about a database right now. It isn't necessary for having the bot up and running. Plus, I think we might switch to an SQLite database at some point.

**Comment by matthieugrieger** [comment]
The bot will not run without a database. The database keeps record of the available translations. Some code changes would need to be made in order to run the bot without having a PostgreSQL database connected to it.

**Comment by adamgrieger** [comment]
Ah, my bad. I thought you said the database was just for tracking usage.

**Comment by matthieugrieger** [comment]
It used to be. I forgot that I had refactored the translation lookup code into searching in the database as opposed to looking within an in-memory data structure. That is why the bot will not work without a database as it sits currently.
