### ISSUE TITLE
Work flow?

### ISSUE THREAD

**Issue by shackra** [Team-VerseBot/versebot#2]
I have never work as part of a team on Github, so I'm new to this.

Looking on the net I discover a work flow called [gitflow](https://vimeo.com/16018419) which seems pretty neat. I mentioned this to @adamgrieger on [Reddit](https://www.reddit.com/r/VerseBot/comments/3qb5to/to_everyone_who_is_considering_working_on/cwe20sy) and he is doing some research on this topic. We should continue that conversation here.

**Comment by adamgrieger** [comment]
I think for the scale of the project it would be fine for us to directly commit to the `dev` branch for smaller things like fixes, typos, and small features. For larger features or features that are more extensive, forking and then submitting a pull request later could work well. Then when the `dev` branch is tested and a new stable build exists, we can merge the `dev` branch changes into the `main` branch.

GitHub has built in integration with a lot of different services, so I might try to find one that is a simple discussion board of sorts where we can say what we are working on or plan on working on so that there aren't a lot of overlapping code changes.

Later on down the road, I think we could look into something like Travis CI for automatically testing builds of VerseBot. It's not necessary, but I think it would be useful. I think when connected to GitHub, it will show the build status after a pull request and things like that.

These are just my ideas for now, anyways. We can go with the flow and figure things out. There isn't any rush.

**Comment by adamgrieger** [comment]
I have been thinking a little more about where to push commits and such, and I think that we could have feature branches in the main repository. Then the people working on those features can push directly to that branch, and then when the feature is ready, the branch can easily be merged. What do you think?

**Comment by matthieugrieger** [comment]
@adamgrieger: That would be the best way to do it (the 2nd comment).

**Comment by shackra** [comment]
So, how are we about this?

**Comment by adamgrieger** [comment]
@shackra, I think making feature branches is the way to go. I am not sure with the current member permissions whether you can make separate branches on the main repo or not. It could just be an admin privilege. You can see that I have been working on a `feature-sqlite3` branch in the meantime on the main repo. Having all of the feature branches in the main repo would be easy to see what other people are working on, but I think having personal branches and then doing a pull request is fine too.

**Comment by shackra** [comment]
My guess is that any member of the team can create branches.

Are we going to use a mailing list for discussing anything worth discussing related to the project or should we keep this in the bug tracker but using a label called "discuss" (the label doesn't exists yet, and I cannot create it)?

**Comment by adamgrieger** [comment]
I'll look and see if there is some service that can be integrated into GitHub that basically functions as a discussion board. If not, we could create an "discussion" issue.

**Comment by adamgrieger** [comment]
@shackra, Take a look at [Slack](https://slack.com/is). I think that would be pretty nice.

**Comment by shackra** [comment]
what about using [Telegram](https://telegram.org/) instead? we can use the [Integram](https://integram.org/) bot to get notifications about anything related to the development of the project, plus, you can use Telegram in your [desktop](https://desktop.telegram.org/) or phone.

**Comment by adamgrieger** [comment]
That could work too. I was mainly looking at Slack, because it is in the GitHub Integrations tab, and it can be directly added to the project. Slack also has an app and stuff.

**Comment by shackra** [comment]
My worry if the app is Free Software, as I only use Free Software on my laptop for ethical reasons.

El sábado 07 de noviembre del 2015 a las 2105 horas, Adam Grieger escribió:

> That could work too. I was mainly looking at Slack, because it is in the GitHub Integrations tab, and it can be directly added to the project. Slack also has an app and stuff.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Team-VerseBot/versebot/issues/2#issuecomment-154772367

-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by adamgrieger** [comment]
Slack has different pricing options including a free tier. The free tier is all that's needed anyways, so it wouldn't cost anybody anything including that the app itself is free, etc.

**Comment by matthieugrieger** [comment]
@adamgrieger: I think @shackra is referring to free, open-source software ([link](https://en.wikipedia.org/wiki/Free_software)).

**Comment by shackra** [comment]
yes, thank you @matthieugrieger! I actually use a laptop that have no BIOS but Grub as payload.

@adamgrieger I found a not-proprietary desktop client for Slack called [ScudCloud](https://github.com/raelgc/scudcloud), I have no issue using the proprietary client of Slack for Android, thought.

If the team want to go for the Slack route, there shouldn't be any problem :).

(I still prefer Telegram+Integram solution thought...)

**Comment by adamgrieger** [comment]
I went ahead and made a Slack team. Slack seems to be more fleshed out and centralized, since GitHub integration is natively built in. I need to go over the settings and create the channels, but it should be on the README.md fairly soon.
